version = 1

[*]
jinja = true
log-colors = on
log-verbosity = 4
fit-target = 256  # Increase this if llama.cpp crashes with out-of-memory errors
flash-attn = on
models-max = 1

# Setting informed by https://github.com/ggml-org/llama.cpp/pull/7412#issuecomment-2120427347
# TODO: Change to Turboquant once merged into llama.cpp main branch
cache-type-k = q8_0
cache-type-v = q8_0
# Almost half the size and the degradation from q8_0 is not measurable with
# llama-perplexity, but the whole internet says they're terrible?!?
; cache-type-k = q4_0
; cache-type-v = q4_0

[Qwen3.6]
# The best quality model that is still performant on less
# than 24 GiB VRAM, as of 2026-06-02
# Choose a quantization
# All measures are from llama-benchy on a RTX 3080 10GiB
# at --cache-type-k = q8_0 --cache-type-v = q8_0

#       bpw   GiB     acc  perplexity  tok/s  notes
# (1)  5.16  22.9  99.35%   6.73±0.04   28±3  Layers don't fit in VRAM
# (2)  4.09  18.2  99.46%   6.89±0.05   30±3  Layers don't fit in VRAM
# (3)  3.97  17.6  98.71%   7.03±0.05   45±3
# (4)  3.06  13.6  96.00%   7.30±0.05   55±4

; hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL  # (1)
; hf = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-IQ4_XS  # (2)
hf = byteshape/Qwen3.6-35B-A3B-MTP-GGUF:Qwen3.6-35B-A3B-IQ4_XS-3.97bpw  # (3)
; hf = byteshape/Qwen3.6-35B-A3B-MTP-GGUF:Qwen3.6-35B-A3B-IQ3_S-3.06bpw  # (4)

; ctx-size = 262144  # 256k recommended on 12 GiB+ VRAM
ctx-size = 131072  # 128k recommended on 8~10 GiB VRAM

image-min-tokens = 1024
spec-type = draft-mtp
spec-draft-n-max = 3
no-mmap = true
# Comment out to move mmproj to VRAM for faster image analysis
no-mmproj-offload = true

# Choose one set of parameters depending on usage
# From https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF

# Thinking mode for general tasks
; temperature = 1.0
; top_p = 0.95
; top_k = 20
; min_p = 0.0
; presence_penalty = 1.5
; repeat_penalty = 1.0

# Thinking mode for precise coding tasks 
temperature = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

# Instruct (or non-thinking) mode for general tasks
; temperature = 0.7
; top-p = 0.8
; top-k = 20
; min-p = 0.0
; presence-penalty = 1.5
; repeat-penalty = 1.0

# Instruct (or non-thinking) mode for reasoning tasks
; temperature = 1.0
; top-p = 0.95
; top-k = 20
; min-p = 0.0
; presence-penalty = 1.5
; repeat-penalty = 1.0

[LFM2.5]
# A very fast but not very capable model;
# not recommended for coding; decent tool use
# https://www.liquid.ai/blog/lfm2-5-8b-a1b
# 5.2 GiB, 318±3 tok/s
hf = unsloth/LFM2.5-8B-A1B-GGUF:UD-Q4_K_M
ctx-size = 131072
temperature = 0.2
top-k = 80
repeat-penalty = 1.05

[MiniCPM5-1B]
# 0.7 GiB, 523±34 tok/s
# Tool use not compatible with llamacpp
hf = openbmb/MiniCPM5-1B-GGUF:Q4_K_M
ctx-size = 131072

# Think
reasoning = on
temperature = 0.9
top-p = 0.95

# No Think
; reasoning = off
; temperature = 0.7
; top-p = 0.95

[Gemma4-E4B]
# 5.5 GiB, 124±3 tok/s 
hf = unsloth/gemma-4-E4B-it-GGUF:Q4_K_M
temperature = 1.0
top-p = 0.95
top-k = 64
