version = 1

[*]
jinja = true
log-colors = on
log-verbosity = 4
fit-target = 256
cache-type-k = q8_0
cache-type-v = q8_0
flash-attn = on
models-max = 1

[byteshape/Qwen3.6-35B-A3B-MTP-GGUF:53BPW]
# The alias is used by llama-benchy; do not change
alias = Qwen/Qwen3.6-35B-A3B-FP8
ctx-size = 131072
image-min-tokens = 1024
spec-type = draft-mtp
spec-draft-n-max = 3
no-mmproj-offload = true
no-mmap = true

[unsloth/LFM2.5-8B-A1B-GGUF:Q4_K_M]
# The alias is used by llama-benchy; do not change
alias = LiquidAI/LFM2.5-8B-A1B
ctx-size = 131072
