[workspace]
channels = ["https://prefix.dev/conda-forge"]
preview = ["pixi-build"]
platforms = ["linux-64"]

[workspace.build-variants]
backend = ["cuda"]

[feature.llama.dependencies]
llama-cpp = { path = "pixi-recipes/llama-cpp" }

[feature.llama.tasks]
list-devices = "llama-server --list-devices"
serve = "llama-server --models-preset models.ini"

[feature.pi.dependencies]
pi-coding-agent = "*"
pi-extensions = { path = "pixi-recipes/pi-extensions" }
bubblewrap = "*"

[feature.pi.tasks]
pi = { cmd = "scripts/bwrap-pi.sh {{ root_dir }}", args = [{ arg = "root_dir", default = "-" }] }
unsafe-pi = { cmd = "scripts/unsafe-pi.sh {{ root_dir }}", args = [{ arg = "root_dir", default = "-" }] }
pi-export = "pi --export"

[feature.openclaw.dependencies]
openclaw = { path = "pixi-recipes/openclaw" }

[feature.llama-benchy.dependencies]
python = "=3.14"

[feature.llama-benchy.pypi-dependencies]
llama-benchy = "*"

[feature.llama-benchy.tasks]
llama-benchy = "python -m llama_benchy --base-url http://localhost:8080"

[environments]
llama = [ "llama", ]
llama-benchy = [ "llama-benchy" ]
pi = [ "pi" ]
openclaw = [ "openclaw" ]
