context:
  version: "9305"
  base_url: https://github.com/ggml-org/llama.cpp/releases/download/b${{ version }}

package:
  name: llama-cpp
  version: ${{ version }}

source:
  # Download and repackage pre-built binaries from
  # https://github.com/ggml-org/llama.cpp/releases
  - if: backend == "cpu"
    then:
      url: ${{ base_url }}/llama-b${{ version }}-bin-ubuntu-x64.tar.gz
      sha256: 0a32013a7cca1c51652bba69799d793886372ec922dbc3aa0788a1f45a7059ba
  - if: backend == "vulkan"
    then:
      url: ${{ base_url }}/llama-b${{ version }}-bin-ubuntu-vulkan-x64.tar.gz
      sha256: 98e5edcf2f5d5e3d41aa791af0bc73d1ff8269e40b48558517cbe746982cfa37
  - if: backend == "rocm"
    then:
      url: ${{ base_url }}/llama-b${{ version }}-bin-ubuntu-rocm-7.2-x64.tar.gz
      sha256: 0805b002e8439cc5a95ef360382c2ad83236e9b8acd164af7faf76bbfe0f5076

build:
  number: 0
  string: ${{ backend }}_h${{ hash }}_${{ build_number }}
  script:
    file: build.sh

about:
  homepage: https://github.com/ggml-org/llama.cpp
  license: MIT
  license_file: LICENSE
  summary: LLM inference in C/C++ (${{ backend }} build)
