context:
  # Main branch
  # fork: ggml-org/llama.cpp
  # version: b9721

  # Famous Turboquant fork
  # Last sync with main at b9632 (2026-06-14)
  fork: TheTom/llama-cpp-turboquant
  version: feature-turboquant-kv-cache-b9905-4595fff

  # https://github.com/ggml-org/llama.cpp/pull/21067
  # Forked from main at b8533 (2026-03-26)
  # fork: am17an/llama.cpp
  # version: 4d78c9d1826b9ee4f058a441c8d4ff9c079fd822

  # TheTom/llama-cpp-turboquant@turboquant-kv-cache + deltas b9632->9698
  # fork: crusaderky/llama.cpp
  # version: b9698-turboquant

  # PR#21067 + deltas b8533->9698
  # fork: crusaderky/llama.cpp
  # version: b9698-bunch-moe-transfer

  # Turboquant + PR#21067 + deltas to 9698
  # fork: crusaderky/llama.cpp
  # version: b9698-staging

  backend: cpu

package:
  name: llama-cpp
  version: ${{ version }}

source:
  git: https://github.com/${{ fork }}
  rev: ${{ version }}

build:
  number: 0
  string: ${{ backend }}_${{ build_number }}
  script:
    file: ../build.sh
    env:
      BACKEND: ${{ backend }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - if: backend == "cuda"
      then:
        - cuda-nvcc
        - cuda-version =12.6
    - if: backend == "vulkan"
      then:
        - shaderc
  host:
    - libcurl
    - openssl
    - if: backend == "cuda"
      then:
        - cuda-version =12.6
        - cuda-cudart-dev
        - libcublas-dev
        - libcurand-dev
    - if: backend == "vulkan"
      then:
        - libvulkan-headers
        - libvulkan-loader
        - spirv-headers
        - spirv-tools
  run:
    - libcurl
    - if: backend == "cuda"
      then:
        - cuda-cudart
        - libcublas
        - libcurand
    - if: backend == "vulkan"
      then:
        - libvulkan-loader

about:
  homepage: https://github.com/ggml-org/llama.cpp
  license: MIT
  license_file: LICENSE
  summary: LLM inference in C/C++
