context:
  version: b9585
  backend: cpu

package:
  name: llama-cpp
  version: ${{ version }}

source:
  git: https://github.com/ggml-org/llama.cpp
  rev: d73cd076740db9c111d0e58ddd4486904469e75e

build:
  number: 0
  string: ${{ backend }}_${{ build_number }}
  script:
    file: ../build.sh
    env:
      BACKEND: ${{ backend }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - if: backend == "cuda"
      then:
        - cuda-nvcc
        - cuda-version =12.6
    - if: backend == "vulkan"
      then:
        - shaderc
  host:
    - libcurl
    - openssl
    - if: backend == "cuda"
      then:
        - cuda-version =12.6
        - cuda-cudart-dev
        - libcublas-dev
        - libcurand-dev
    - if: backend == "vulkan"
      then:
        - libvulkan-headers
        - libvulkan-loader
        - spirv-headers
        - spirv-tools
  run:
    - libcurl
    - if: backend == "cuda"
      then:
        - cuda-cudart
        - libcublas
        - libcurand
    - if: backend == "vulkan"
      then:
        - libvulkan-loader

about:
  homepage: https://github.com/ggml-org/llama.cpp
  license: MIT
  license_file: LICENSE
  summary: LLM inference in C/C++
