context:
  version: b9585
  backend: rocm
  variant_tag: ubuntu-rocm-7.2-x64

package:
  name: llama-cpp
  version: ${{ version }}

source:
  url: https://github.com/ggml-org/llama.cpp/releases/download/${{ version }}/llama-${{ version }}-bin-${{ variant_tag }}.tar.gz
  sha256: e1b4f11db56506da9edcb6c68818c8b54c5a08a3b4e558554aeea1c874b4ef4a

build:
  number: 0
  string: ${{ backend }}_${{ build_number }}
  script:
    file: ../build.sh

about:
  homepage: https://github.com/ggml-org/llama.cpp
  license: MIT
  license_file: LICENSE
  summary: LLM inference in C/C++
