[workspace]
channels = ["https://prefix.dev/conda-forge"]
preview = ["pixi-build"]
platforms = ["linux-64", "win-64"]

[workspace.build-variants]
backend = ["cpu", "cuda", "vulkan"]

[package.build.backend]
name = "pixi-build-rattler-build"
version = "*"
