context:
  version: "9360"
  base_url: https://github.com/ggml-org/llama.cpp/releases/download/b${{ version }}

package:
  name: llama-cpp
  version: ${{ version }}

source:
  # Download and repackage pre-built binaries from
  # https://github.com/ggml-org/llama.cpp/releases
  - if: backend == "cpu"
    then:
      url: ${{ base_url }}/llama-b${{ version }}-bin-ubuntu-x64.tar.gz
      sha256: cc2a0a5ded40bc1a815fc4f8c9836cddb82a2cce1716bf825dfe61d31ebd9117
  - if: backend == "vulkan"
    then:
      url: ${{ base_url }}/llama-b${{ version }}-bin-ubuntu-vulkan-x64.tar.gz
      sha256: 490d3617a15b497008170634372fbedd1f0996b14c27b82b6a8d661bba1a218c
  - if: backend == "rocm"
    then:
      url: ${{ base_url }}/llama-b${{ version }}-bin-ubuntu-rocm-7.2-x64.tar.gz
      sha256: 5db9dcf5fa646a0febe686e4987c1995f2e7f362fb4221f0e67162b8f70dbb2e

build:
  number: 0
  string: ${{ backend }}_${{ build_number }}
  script:
    file: build.sh

about:
  homepage: https://github.com/ggml-org/llama.cpp
  license: MIT
  license_file: LICENSE
  summary: LLM inference in C/C++ (${{ backend }} build)
